import { BRAND } from "../brand";

// Clinician sign-up and onboarding (N5). Problem keys match the codes the core schema and services throw.
export const ONBOARDING = {
  signup: {
    title: "Start free.",
    lead: "Just your email. No card, no password. We'll send a link that signs you in.",
    emailLabel: "Your work email",
    send: "Send me a link",
    sentTitle: "Check your email.",
    sent: (to: string) => `We sent a link to ${to}. It works once and lasts 15 minutes.`,
    continueAs: (email: string) => `Continue as ${email}`,
    betaOnly: `${BRAND.name} is letting clinicians in a few at a time during the beta. We'll email you as soon as there's room.`,
    otherRole: `This email already has a client account on ${BRAND.name}. To join as a clinician, sign up with a different email.`,
    problem: "That didn't go through. One more try?",
  },
  steps: ["Agreements", "Practice", "Fees", "Filing"] as const,
  agree: {
    title: "First, the paperwork.",
    lead: "Our terms, and the business associate agreement that covers your clients' information.",
    nameLabel: "Type your full name to sign",
    submit: "Agree and continue",
    draft: "Draft",
  },
  passkey: {
    title: "Sign in with Face ID or Touch ID.",
    lead: "Add a passkey and next time you're in with a glance, no email needed.",
  },
  practice: {
    title: "Your practice.",
    lead: "Claims go out under these details, so they need to match what your insurers have on file.",
    legalName: "Your name as it appears on your license",
    credential: "Credential",
    credentialHint: "For example LCSW, LMFT, PsyD",
    npi: "Your individual NPI",
    npiType: "Your clients' claims bill under",
    npiTypes: { individual: "My own NPI", group: "My group's NPI" },
    groupName: "Group name",
    groupNpi: "Group NPI",
    taxIdType: "Tax ID type",
    taxIdTypes: { EIN: "EIN", SSN: "SSN" },
    taxId: "Tax ID",
    taxIdHint: "We keep it encrypted and only ever show the last four.",
    taxIdOnFile: (last4: string) => `On file: ending ${last4}. Leave blank to keep it.`,
    address: "Practice address",
    line1: "Street address",
    line2: "Suite or unit (optional)",
    city: "City",
    state: "State",
    zip: "ZIP code",
    licenseState: "License state",
    licenseNumber: "License number",
    taxonomy: "Specialty",
    noteFormat: "Default note format",
    modality: "Where you usually see clients",
    submit: "Save and continue",
    save: "Save changes",
  },
  fees: {
    title: "Your session fees.",
    lead: "What you charge for each kind of session. Claims use the fee as it stands when they're built.",
    none: "Set a fee for at least one kind of session.",
    submit: "Save and continue",
    save: "Save fees",
  },
  authorize: {
    title: "Last step: let us file for you.",
    lead: "This lets us send your clients' claims under your NPI. Clients stay the payee; you never take assignment.",
    nameLabel: "Type your full name to sign",
    submit: "Sign and finish",
  },
  saved: "Saved.",
  problems: {
    npi_format: "An NPI is 10 digits.",
    npi_check: "That NPI doesn't check out. Look over the 10 digits and try again.",
    npi_taken: `That NPI is already on another ${BRAND.name} account. If it's yours, write to us and we'll sort it out.`,
    group_name_required: "Add your group's name.",
    group_npi_check: "That group NPI doesn't check out. Look over the 10 digits and try again.",
    group_npi_same: "Your group's NPI is different from your own.",
    group_needs_ein: "A group bills under its EIN.",
    tax_id_format: "A Tax ID is 9 digits.",
    tax_id_required: "Add your Tax ID.",
    tax_id_changed: "You changed how your claims bill, so enter the Tax ID they bill under.",
    zip_format: "A ZIP code is 5 digits.",
    invalid: "Some of that didn't look right. Check the highlighted fields.",
    no_fees: "Set a fee for at least one kind of session.",
    fee_format: "Fees are dollar amounts, like 175 or 175.50.",
    no_name: "Type your name to sign.",
    text_changed: "That text just changed. Here's the latest.",
    no_intent: "Start from the sign-up page so we know you're joining as a clinician.",
    other_role: `This email already has a client account on ${BRAND.name}. To join as a clinician, sign up with a different email.`,
    legal_placeholder: `${BRAND.name} isn't open for sign-ups yet. We'll email you as soon as it is.`,
    incomplete: "A step above still needs finishing.",
  },
} as const;

export type OnboardingProblem = keyof typeof ONBOARDING.problems;
export const isOnboardingProblem = (v: unknown): v is OnboardingProblem => typeof v === "string" && Object.hasOwn(ONBOARDING.problems, v);
